version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_dbt
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: dbt_database
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dbt_net

networks:
  dbt_net:
    external: true

volumes:
  postgres_data:
