name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    +materialized: table 
    #+schema: "" 
    

vars:
  loadsmart_schemas:
    - loadsmart_dim
    - loadsmart_fact
    - loadsmart_anl
    - loadsmart_reports

on-run-start:
  - >
    {%- for sch in var('loadsmart_schemas') %}
      CREATE SCHEMA IF NOT EXISTS {{ sch }};
    {%- endfor %}
