dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: dbt_user
      pass: dbt_password
      port: 5432
      dbname: dbt_database
      schema: public
      threads: 4

